baseURL = 'https://viciouseagle03.github.io/'
languageCode = 'en-us'
title = 'Piyush Sharma'
theme = 'paper' 

[params]
  # header social icons
  github = 'ViciousEagle03'
  instagram = 'piyushs_03'
  linkedin = 'piyush-sharma-0b559a250'
  rss = true

  # home page profile
  avatar = "https://rukminim2.flixcart.com/image/850/1000/kz4gh3k0/poster/j/x/1/medium-cat-glasses-space-abstract-matte-finish-poster-original-imagb787bgsvyeg7.jpeg?q=90&crop=false"
  name = 'VEagle03'
  bio = "Hey there! Welcome to my blog. Stay tuned for updates and posts coming your way soon!"

[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
    
[[menu.main]]
    name = "About"
    weight = 2
    identifier = "about"
    url = "/about"


